defmodule PhoenixHologramWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :phoenix_hologram

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_phoenix_hologram_key",
    signing_salt: "rXyj+iDe",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Companion Android app connects here to report UPI payment
  # confirmations it read from SMS notifications — see PaymentSocket.
  socket "/payment_socket", PhoenixHologramWeb.PaymentSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :phoenix_hologram,
    gzip: not code_reloading?,
    only: PhoenixHologramWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId

  # Traffic reaches Bandit through a local proxy/tunnel (dev port-forwarding,
  # or any reverse proxy in front of this app), so conn.remote_ip is that
  # proxy's own loopback address, not the actual visitor's. RemoteIp rewrites
  # it from X-Forwarded-For, but only when the direct peer is itself a
  # trusted proxy (loopback/private ranges by default) - an internet client
  # can't spoof its way past that by sending its own X-Forwarded-For header.
  plug RemoteIp

  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # `:length` raised past Plug.Parsers' 8MB default to comfortably fit
  # one VideoUploadController chunk (PhoenixHologram.VideoUpload.chunk_size/0,
  # 40MB) plus multipart overhead — videos upload in chunks specifically
  # so no single request ever needs to carry more than that, keeping
  # every request well under proxy body-size caps like Cloudflare's
  # 100MB limit regardless of this setting.
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    length: 50_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug PhoenixHologramWeb.Plugs.PageVisitLogger
  plug Hologram.Router
  plug PhoenixHologramWeb.Router
end
